---
title: "Publications"
---

Please find my Google Scholar profile [here](https://scholar.google.com/citations?hl=en&user=ScAs7hoAAAAJ). 

### Peer Reviewed Publications

Singh, I., Shah, R., Stoms, M., **Fowler, C**., Vohra, A., Yip, L., ... & Menon, V. (2025). Unveiling the link: social determinants of health, quality of life, and burden of treatment in heart failure patients. *American Journal of Cardiovascular Disease*, 15(2), 69.[https://pmc.ncbi.nlm.nih.gov/articles/PMC12089017/](https://pmc.ncbi.nlm.nih.gov/articles/PMC12089017/) 

**Fowler, C.**, Cai, X., Baker, J. T., Onnela, J. P., \& Valeri, L. (2024). Testing unit root non-stationarity in the presence of missing data in univariate time series of mobile health studies. *Journal of the Royal Statistical Society Series C: Applied Statistics*. [https://doi.org/10.1093/jrsssc/qlae010](https://doi.org/10.1093/jrsssc/qlae010) 

Pitts, A. J., \& **Fowler, C. R.** (2024).  Comparison of open-source software for producing directed acyclic graphs.  *Journal of Causal Inference*. [https://doi.org/10.1515/jci-2023-0031](https://doi.org/10.1515/jci-2023-0031)

Rogers, R. T., Rogers, R., DeSilva, N., **Fowler, C. R.**, Marino, L. (2023). Prevalence of tobacco smoking among U.S. residents with primary psychosis: A systematic review of national and regional samples. *Current Psychology*. [https://doi.org/10.1007/s12144-023-05290-w](https://doi.org/10.1007/s12144-023-05290-w) 

Mosinger, E., Thaler, K., Paz Garcia, D., 
**Fowler, C.** (2022). Civil Resistance in the Shadow of the Revolution: Historical Framing in Nicaragua’s Sudden Uprising. *Comparative Politics, 54.1*. [https://doi.org/10.5129/001041522X16281740895086](https://doi.org/10.5129/001041522X16281740895086) 

**Fowler, C.**, Homandberg, L., Steele, C., Bolt, M.A., Tintle, N., Ulrich, R., Christians, M. (2020). Adult correlates of adverse childhood experiences in Ukraine. *Child Abuse \& Neglect, 107*. [https://doi.org/10.1016/j.chiabu.2020.104617](https://doi.org/10.1016/j.chiabu.2020.104617) 

### Manuscripts under Review

**Fowler, C. R.**, Cai, X., Rahimi-Eichi, H., Dixon, L., Baker, J. T., Onnela, J. P., & Valeri, L. (2025). Individual causal effect estimation accounting for latent disease state modification among bipolar participants in mobile health studies. [https://doi.org/10.48550/arXiv.2501.08270](https://doi.org/10.48550/arXiv.2501.08270)

Cai, X., **Fowler, C. R.**, Zeng, L., Eichi, H. R., Ongur, D., Dixon, L., ... & Valeri, L. (2025). Missing data in non-stationary multivariate time series from digital studies in Psychiatry. arXiv preprint arXiv:2506.14946. [https://doi.org/10.48550/arXiv.2506.14946](https://doi.org/10.48550/arXiv.2506.14946)

Cai, X., Zeng, L., **Fowler, C.**, Dixon, L., Ongur, D., Baker, J.T., Onnela, J.P. and Valeri, L. (2024). Causal estimands and identification of time-varying effects in non-stationary time series from N-of-1 mobile device data.  [https://arxiv.org/abs/2407.17666](https://arxiv.org/abs/2407.17666)

### Manuscripts in Preparation

**Fowler, C.R.**, Rahimi-Eichi, H., Cai, X., Baker J.T., Onnela, J.P.,  Goldsmith, J., and  Valeri, L. (2025). Functional data analysis approach for individual causal mediation analysis in N-of-1 mobile health studies.  

Kimhy, D., **Fowler, C.R.**, Valeri, L., Rogers, R.S., Xu, X., Buchsbaum, R., Stefancic, A., Cabassa, L.J., Nossell, I., and Stroup T.S. (2025) First Episode Psychosis Digital Monitoring: Feasibility, Compliance, and Response Variability.

Kimhy, D., **Fowler, C.R.**, Valeri, L., Rogers, R.S., Xu, X., Buchsbaum, R., Stefancic, A., Cabassa, L.J., Nossell, I., and Stroup T.S. (2025) Real-Time Medication Side Effects in Individuals with First Episode Psychosis: Daily Course, Variance, Impact on Functioning, and Comparison to Retrospective Ratings.


