---
title: "Teaching"
---

<font size = "4">

<br>

### Worcester Polytechnic Institute Teaching

Applied Statistics I (MA 2611), Fall 2024 B term, Spring 2025 D term, and Fall 2025 A term

Principles of Epidemiology (MA 544/SS 510), Spring 2025


<br>


### Columbia University Teaching

I served as instructor for the Introduction to Biostatistics course in the summers of 2022 and 2023 for the [Biostatistics Epidemiology Summer Training](https://www.publichealth.columbia.edu/research/programs/biostatistics-epidemiology-summer-training). This summer program offers exposure and training in biostatistics, coding, and epidemiology for 13-15 undergraduates from under-represented backgrounds. In this role I designed and developed the course materials and [syllabus](docs_to_link/syllabus.pdf), delivered lectures, managed teaching assistants, and mentored students. The introductory course covered methods for
describing discrete and continuous data, hypothesis testing, confidence intervals, general
principles of study design, and regression models. 

</font>

<br>


### Teaching Assistant Experience 

<font size = "4">

Topics in Advanced Statistical Computing (P8160), Spring 2022

Probability (P8104), Lead TA, Fall 2020 and Fall 2021

Latent Variable and Structural Equation Modeling (P8158), Spring 2021

Columbia Summer Research Institute Biostatistics and Epidemiology (Introduction to Biostatistics; Introduction to Epidemiology), Summer 2020

Introduction to Health Data Science (P8101), Spring 2020

</font>
